CREATE TABLE FCT_IDV_LBY_AR
(
    FCT_EFF_DT DATETIME,
    LBY_AR_ID INT,
    PNP_AMT INT
)

CREATE TABLE DIM_IDV_LBY_AR
(
    DIM_EFF_DT DATETIME,
    DIM_END_DT DATETIME,
    LBY_AR_ID INT,
    CST_ID INT,
    PD_ID INT,
    PRC FLOAT(24)
)

CREATE TABLE DIM_IDV_PD
(
    PD_ID INT,
    NM CHAR(30)
)