SELECT CST_ID, FCT_EFF_DT, PD_ID, SUM(PNP_AMT) AS SUM_PNT_AVG, AVG(PRC) AS AVG_PRC
FROM FCT_IDV_LBY_AR AS f
LEFT JOIN DIM_IDV_LBY_AR AS d
ON f.FCT_EFF_DT BETWEEN d.DIM_EFF_DT AND d.DIM_END_DT
AND f.LBY_AR_ID = d.LBY_AR_ID
GROUP BY FCT_EFF_DT, CST_ID, PD_ID