WITH PD AS (
SELECT PD_ID AS PD1
FROM DIM_ORG_LBY_AR
GROUP BY PD_ID
UNION
SELECT PD_ID 
FROM DIM_ORG_LOAN_AR
GROUP BY PD_ID
UNION
SELECT PD_ID 
FROM DIM_ORG_GNT_AR
GROUP BY PD_ID
)

SELECT p.PD1, ((SELECT PD_ID, COUNT(DISTINCT(CST_ID)) FROM DIM_ORG_LBY_AR WHERE '20180321' BETWEEN EFF_DT AND END_DT GROUP BY PD_ID) UNION
(SELECT PD_ID COUNT(DISTINCT(CST_ID)) FROM DIM_ORG_LOAN_AR WHERE '20180321' BETWEEN EFF_DT AND END_DT GROUP BY PD_ID) UNION
(SELECT PD_ID COUNT(DISTINCT(CST_ID)) FROM DIM_ORG_GNT_AR WHERE '20180321' BETWEEN EFF_DT AND END_DT AND PD_ID = p.PD1 GROUP BY PD_ID) WHERE PD_ID = p.PD1) AS CNT_CST,

((SELECT COUNT(CST_ID) FROM DIM_ORG_LBY_AR WHERE '20180321' BETWEEN EFF_DT AND END_DT AND PD_ID = p.PD1 GROUP BY CST_ID) +
(SELECT COUNT(CST_ID) FROM DIM_ORG_LOAN_AR WHERE '20180321' BETWEEN EFF_DT AND END_DT AND PD_ID = p.PD1 GROUP BY CST_ID) +
(SELECT COUNT(CST_ID) FROM DIM_ORG_GNT_AR WHERE '20180321' BETWEEN EFF_DT AND END_DT AND PD_ID = p.PD1 GROUP BY CST_ID)) AS CNT_AR
FROM PD AS p
GROUP BY p.PD1

