
SELECT do.ORG_ID, ((SELECT SUM(DB_AMT) FROM PST_ENTR WHERE DATEDIFF(DAY, PST_DT, '20200321') < 31 AND CR_AC_NBR IN 
(SELECT AR_CODE FROM DIM_ORG_LBY_AR AS dola WHERE dola.CST_ID = do.ORG_ID AND dola.EFF_DT < '20200321' AND dola.LBY_AR_TP = 3))
- (SELECT SUM(DB_AMT) FROM PST_ENTR WHERE DATEDIFF(DAY, PST_DT, '20200321') < 31 AND DB_AC_NBR IN 
(SELECT AR_CODE FROM DIM_ORG_LBY_AR AS dola WHERE dola.CST_ID = do.ORG_ID AND dola.EFF_DT < '20200321' AND dola.LBY_AR_TP = 3))) AS AMT_PST,

((SELECT COUNT(*) FROM PST_ENTR WHERE DATEDIFF(DAY, PST_DT, '20200321') < 31 AND (CR_AC_NBR IN 
(SELECT AR_CODE FROM DIM_ORG_LBY_AR AS dola WHERE do.ORG_ID = dola.CST_ID AND dola.EFF_DT < '20200321' AND dola.LBY_AR_TP = 3))
OR DB_AC_NBR IN
(SELECT AR_CODE FROM DIM_ORG_LBY_AR AS dola WHERE do.ORG_ID = dola.CST_ID AND dola.EFF_DT < '20200321' AND dola.LBY_AR_TP = 3))) AS CNT_PST,

((SELECT MAX(PST_DT) FROM PST_ENTR WHERE PST_DT < '20200321' AND CR_AC_NBR IN 
(SELECT AR_CODE FROM DIM_ORG_LBY_AR AS dola WHERE do.ORG_ID = dola.CST_ID AND dola.EFF_DT < '20200321' AND dola.LBY_AR_TP = 3))) AS LAST_CR_PST_DT,

((SELECT MAX(PST_DT) FROM PST_ENTR WHERE PST_DT < '20200321' AND DB_AC_NBR IN 
(SELECT AR_CODE FROM DIM_ORG_LBY_AR AS dola WHERE do.ORG_ID = dola.CST_ID AND dola.EFF_DT < '20200321' AND dola.LBY_AR_TP = 3))) AS LAST_DB_PST_DT,

(SELECT CASE WHEN ((SELECT MIN(EFF_DT) FROM DIM_ORG_LBY_AR WHERE EFF_DT < '20200321' AND CST_ID = do.ORG_ID) < 
(SELECT MIN(EFF_DT) FROM DIM_ORG_LOAN_AR WHERE EFF_DT < '20200321' AND CST_ID = do.ORG_ID)) AND
((SELECT MIN(EFF_DT) FROM DIM_ORG_LBY_AR WHERE EFF_DT < '20200321' AND CST_ID = do.ORG_ID) < 
(SELECT MIN(EFF_DT) FROM DIM_ORG_GNT_AR WHERE EFF_DT < '20200321' AND CST_ID = do.ORG_ID)) THEN 
(SELECT MIN(EFF_DT) FROM DIM_ORG_LBY_AR WHERE EFF_DT < '20200321' AND CST_ID = do.ORG_ID) ELSE
(SELECT CASE WHEN ((SELECT MIN(EFF_DT) FROM DIM_ORG_LOAN_AR WHERE EFF_DT < '20200321' AND CST_ID = do.ORG_ID) < 
(SELECT MIN(EFF_DT) FROM DIM_ORG_LBY_AR WHERE EFF_DT < '20200321' AND CST_ID = do.ORG_ID)) AND
((SELECT MIN(EFF_DT) FROM DIM_ORG_LOAN_AR WHERE EFF_DT < '20200321' AND CST_ID = do.ORG_ID) < 
(SELECT MIN(EFF_DT) FROM DIM_ORG_GNT_AR WHERE EFF_DT < '20200321' AND CST_ID = do.ORG_ID)) THEN 
(SELECT MIN(EFF_DT) FROM DIM_ORG_LOAN_AR WHERE EFF_DT < '20200321' AND CST_ID = do.ORG_ID) ELSE
(SELECT MIN(EFF_DT) FROM DIM_ORG_GNT_AR WHERE EFF_DT < '20200321' AND CST_ID = do.ORG_ID) END)END) AS FRST_AR_EFF_DT,


(SELECT CASE WHEN ((SELECT MAX(EFF_DT) FROM DIM_ORG_LBY_AR WHERE EFF_DT < '20200321' AND CST_ID = do.ORG_ID) > 
(SELECT MAX(EFF_DT) FROM DIM_ORG_LOAN_AR WHERE EFF_DT < '20200321' AND CST_ID = do.ORG_ID)) AND
((SELECT MAX(EFF_DT) FROM DIM_ORG_LBY_AR WHERE EFF_DT < '20200321' AND CST_ID = do.ORG_ID) > 
(SELECT MAX(EFF_DT) FROM DIM_ORG_GNT_AR WHERE EFF_DT < '20200321' AND CST_ID = do.ORG_ID)) THEN 
(SELECT MAX(EFF_DT) FROM DIM_ORG_LBY_AR WHERE EFF_DT < '20200321' AND CST_ID = do.ORG_ID) ELSE
(SELECT CASE WHEN ((SELECT MAX(EFF_DT) FROM DIM_ORG_LOAN_AR WHERE EFF_DT < '20200321' AND CST_ID = do.ORG_ID) > 
(SELECT MAX(EFF_DT) FROM DIM_ORG_LBY_AR WHERE EFF_DT < '20200321' AND CST_ID = do.ORG_ID)) AND
((SELECT MAX(EFF_DT) FROM DIM_ORG_LOAN_AR WHERE EFF_DT < '20200321' AND CST_ID = do.ORG_ID) >
(SELECT MAX(EFF_DT) FROM DIM_ORG_GNT_AR WHERE EFF_DT < '20200321' AND CST_ID = do.ORG_ID)) THEN 
(SELECT MAX(EFF_DT) FROM DIM_ORG_LOAN_AR WHERE EFF_DT < '20200321' AND CST_ID = do.ORG_ID) ELSE
(SELECT MAX(EFF_DT) FROM DIM_ORG_GNT_AR WHERE EFF_DT < '20200321' AND CST_ID = do.ORG_ID) END)END) AS LAST_AR_EFF_DT,

(SELECT CASE WHEN ((SELECT MAX(END_DT) FROM DIM_ORG_LBY_AR WHERE END_DT < '20200321' AND CST_ID = do.ORG_ID) > 
(SELECT MAX(END_DT) FROM DIM_ORG_LOAN_AR WHERE END_DT < '20200321' AND CST_ID = do.ORG_ID)) AND
((SELECT MAX(END_DT) FROM DIM_ORG_LBY_AR WHERE END_DT < '20200321' AND CST_ID = do.ORG_ID) > 
(SELECT MAX(END_DT) FROM DIM_ORG_GNT_AR WHERE END_DT < '20200321' AND CST_ID = do.ORG_ID)) THEN 
(SELECT MAX(END_DT) FROM DIM_ORG_LBY_AR WHERE END_DT < '20200321' AND CST_ID = do.ORG_ID) ELSE
(SELECT CASE WHEN ((SELECT MAX(END_DT) FROM DIM_ORG_LOAN_AR WHERE END_DT < '20200321' AND CST_ID = do.ORG_ID) > 
(SELECT MAX(END_DT) FROM DIM_ORG_LBY_AR WHERE END_DT < '20200321' AND CST_ID = do.ORG_ID)) AND
((SELECT MAX(END_DT) FROM DIM_ORG_LOAN_AR WHERE END_DT < '20200321' AND CST_ID = do.ORG_ID) >
(SELECT MAX(END_DT) FROM DIM_ORG_GNT_AR WHERE END_DT < '20200321' AND CST_ID = do.ORG_ID)) THEN 
(SELECT MAX(END_DT) FROM DIM_ORG_LOAN_AR WHERE END_DT < '20200321' AND CST_ID = do.ORG_ID) ELSE
(SELECT MAX(END_DT) FROM DIM_ORG_GNT_AR WHERE END_DT < '20200321' AND CST_ID = do.ORG_ID) END)END) AS LAST_AR_END_DT

FROM DIM_ORG AS do
WHERE '20200321' BETWEEN do.DIM_EFF_DT AND do.DIM_END_DT
--LEFT JOIN DIM_ORG_LBY_AR AS dola ON ('28880321' BETWEEN do.DIM_EFF_DT AND do.DIM_END_DT) AND do.ORG_ID = dola.CST_ID AND dola.EFF_DT < '28880321'
--LEFT JOIN PST_ENTR AS pe ON (dola.AR_CODE = pe.DB_AC_NBR OR dola.AR_CODE = pe.CR_AC_NBR) AND pe.PST_DT < '28880321'
GROUP BY do.ORG_ID