SELECT ACT_DT, DEP_ID, 
(SELECT VAL_R FROM GD_TD_REG g1 WHERE DEP_REG_ID = 'DP005' AND g1.ACT_DT = g.ACT_DT AND g1.DEP_ID = g.DEP_ID) AS DP005,
(SELECT SUM(VAL_R) FROM GD_TD_REG g2 WHERE DEP_REG_ID = 'DP001' AND g2.DEP_ID = g.DEP_ID AND DATEDIFF(DAY, g2.ACT_DT, g.ACT_DT) < 31 AND DATEDIFF(DAY, g2.ACT_DT, g.ACT_DT) > 0) AS SUM_DP001,
(SELECT SUM(VAL_R) FROM GD_TD_REG g3 WHERE (DEP_REG_ID = 'DP004' OR DEP_REG_ID = 'DP014') AND g3.DEP_ID = g.DEP_ID AND DATEDIFF(DAY, g3.ACT_DT, g.ACT_DT) < 31 AND DATEDIFF(DAY, g3.ACT_DT, g.ACT_DT) > 0) AS SUM_DP004_AND_DP014
FROM GD_TD_REG g
GROUP BY ACT_DT, DEP_ID